### ISSUE TITLE
SWIG director method error.

### ISSUE THREAD

**Issue by valentjn** [SGpp/SGpp#66]
In GitLab by @freifrauvonbleifrei on Aug 21, 2018, 19:43

Hi, 

when trying to run the combigrid examples that are supposed to work on master, this is what happens (still in Python2, because still on `master`):

```
/usr/bin/python2 /home/pollinta/Desktop/SGpp/combigrid/examples/gettingStartedShorter.py
/home/pollinta/.local/lib/python2.7/site-packages/scipy/special/__init__.py:640: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96,got 88
  from ._ufuncs import *

[... a lot more of this same warning in different places ...]

Example 1:
Traceback (most recent call last):
  File "/home/pollinta/Desktop/SGpp/combigrid/examples/gettingStartedShorter.py", line 384, in <module>
    example1()
  File "/home/pollinta/Desktop/SGpp/combigrid/examples/gettingStartedShorter.py", line 70, in example1
    result = operation.evaluate(2)
  File "/home/pollinta/Desktop/SGpp/lib/pysgpp/pysgpp_swig.py", line 20568, in evaluate
    return _pysgpp_swig.CombigridOperation_evaluate(self, *args)
RuntimeError: SWIG director method error.
```

I am trying to find the commit that introduced this, and pointers would be appreciated (compiling takes soooo long!). If you have some idea what is going on, please let us know.

**Comment by valentjn** [comment]
In GitLab by @freifrauvonbleifrei on Aug 21, 2018, 20:12

seems that this was already present at least with 5541bb53f27611126fd5ff39391e9f60d216fc4e ... looking further...

**Comment by valentjn** [comment]
In GitLab by @freifrauvonbleifrei on Aug 21, 2018, 20:50

f963c7adb40c3214e5611344c767b6e1b00ee1fa has its own problems, but since it has all the numpy.dtype warnings it might also have the SWIG error... 

```
~/Desktop/SGpp$ /usr/bin/python2 /home/pollinta/Desktop/SGpp/combigrid/examples/gettingStartedShorter.py
/home/pollinta/.local/lib/python2.7/site-packages/scipy/special/__init__.py:640: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96,got 88
  from ._ufuncs import *
/home/pollinta/.local/lib/python2.7/site-packages/scipy/linalg/basic.py:17: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._solve_toeplitz import levinson
/home/pollinta/.local/lib/python2.7/site-packages/scipy/linalg/__init__.py:207: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._decomp_update import *
/home/pollinta/.local/lib/python2.7/site-packages/scipy/special/_ellip_harm.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._ellip_harm_2 import _ellipsoid, _ellipsoid_norm
/home/pollinta/.local/lib/python2.7/site-packages/scipy/interpolate/_bsplines.py:10: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected96, got 88
  from . import _bspl
/home/pollinta/.local/lib/python2.7/site-packages/scipy/sparse/lil.py:19: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _csparsetools
/home/pollinta/.local/lib/python2.7/site-packages/scipy/sparse/csgraph/__init__.py:165: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._shortest_path import shortest_path, floyd_warshall, dijkstra,\
/home/pollinta/.local/lib/python2.7/site-packages/scipy/sparse/csgraph/_validation.py:5: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._tools import csgraph_to_dense, csgraph_from_dense,\
/home/pollinta/.local/lib/python2.7/site-packages/scipy/sparse/csgraph/__init__.py:167: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._traversal import breadth_first_order, depth_first_order, \
/home/pollinta/.local/lib/python2.7/site-packages/scipy/sparse/csgraph/__init__.py:169: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._min_spanning_tree import minimum_spanning_tree
/home/pollinta/.local/lib/python2.7/site-packages/scipy/sparse/csgraph/__init__.py:170: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._reordering import reverse_cuthill_mckee, maximum_bipartite_matching, \
/home/pollinta/.local/lib/python2.7/site-packages/scipy/spatial/__init__.py:95: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .ckdtree import *
/home/pollinta/.local/lib/python2.7/site-packages/scipy/spatial/__init__.py:96: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .qhull import *
/home/pollinta/.local/lib/python2.7/site-packages/scipy/spatial/_spherical_voronoi.py:18: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _voronoi
/home/pollinta/.local/lib/python2.7/site-packages/scipy/spatial/distance.py:122: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96,got 88
  from . import _hausdorff
/home/pollinta/.local/lib/python2.7/site-packages/scipy/optimize/_trlib/__init__.py:1: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._trlib import TRLIBQuadraticSubproblem
/home/pollinta/.local/lib/python2.7/site-packages/scipy/optimize/_numdiff.py:10: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96,got 88
  from ._group_columns import group_dense, group_sparse
/home/pollinta/.local/lib/python2.7/site-packages/scipy/stats/_continuous_distns.py:18: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _stats
Traceback (most recent call last):
  File "/home/pollinta/Desktop/SGpp/combigrid/examples/gettingStartedShorter.py", line 15, in <module>
    from pysgpp.extensions.datadriven.uq.dists import J, Beta, Uniform
  File "/home/pollinta/Desktop/SGpp/lib/pysgpp/extensions/datadriven/uq/dists/__init__.py", line 45, in <module>
    from DTreesDist import DTreesDist
ImportError: No module named DTreesDist
```

**Comment by valentjn** [comment]
In GitLab by @freifrauvonbleifrei on Aug 21, 2018, 21:02

Again, some import error in 5d88125b60cfd3b84eab7740d70a79ba9993dbc2 , but this time no dtype warnings

```
 /usr/bin/python2 /home/pollinta/Desktop/SGpp/combigrid/examples/gettingStarted.py
Traceback (most recent call last):
  File "/home/pollinta/Desktop/SGpp/combigrid/examples/gettingStarted.py", line 15, in <module>
    from pysgpp.extensions.datadriven.uq.dists import J, Beta, Uniform
  File "/home/pollinta/Desktop/SGpp/lib/pysgpp/extensions/datadriven/uq/dists/__init__.py", line 30, in <module>
    from Beta import Beta
  File "/home/pollinta/Desktop/SGpp/lib/pysgpp/extensions/datadriven/uq/dists/Beta.py", line 18, in <module>
    from Dist import Dist
  File "/home/pollinta/Desktop/SGpp/lib/pysgpp/extensions/datadriven/uq/dists/Dist.py", line 17, in <module>
    from pysgpp.extensions.datadriven.uq.sampler.Sample import Sample, SampleType
  File "/home/pollinta/Desktop/SGpp/lib/pysgpp/extensions/datadriven/uq/sampler/__init__.py", line 1, in <module>
    from MCSampler import MCSampler
  File "/home/pollinta/Desktop/SGpp/lib/pysgpp/extensions/datadriven/uq/sampler/MCSampler.py", line 1, in <module>
    from pysgpp import (DataVector,
ImportError: cannot import name NaiveSampleGenerator
```

**Comment by valentjn** [comment]
In GitLab by @freifrauvonbleifrei on Aug 21, 2018, 21:03

changed the description

**Comment by valentjn** [comment]
In GitLab by @freifrauvonbleifrei on Aug 21, 2018, 21:16

and the same holds for b6ee8e3b2 .

**Comment by valentjn** [comment]
In GitLab by @freifrauvonbleifrei on Aug 21, 2018, 21:31

...and the same for d2c9df1437accb5e9401dc0e714b3f2066b89983 .

**Comment by valentjn** [comment]
In GitLab by @valentjn on Aug 21, 2018, 22:31

You know about `git bisect`? Take a really old commit where you know it worked. Can you turn off some modules?

**Comment by valentjn** [comment]
In GitLab by @spc90 on Aug 22, 2018, 11:22

The ccef8ca0 merge-commit that happened just before my merge commit 5d88125b seems to have working SWIG directors. I did a side-by-side comparison and nothing looked as it would have caused problems, but I am still testing some things...

**Comment by valentjn** [comment]
In GitLab by @spc90 on Aug 22, 2018, 12:43

I am pretty sure I found the problem and fixed it. I am waiting for confirmation from Theresa, and then I will merge the small interface changes into master, so that they can be available in the last working version of SGpp with python v2 as well

**Comment by valentjn** [comment]
In GitLab by @freifrauvonbleifrei on Aug 22, 2018, 13:20

mentioned in merge request !74

**Comment by valentjn** [comment]
In GitLab by @leiterrl on Aug 22, 2018, 13:44

Fixed in !71

**Comment by valentjn** [comment]
In GitLab by @leiterrl on Aug 22, 2018, 13:44

closed
